scenes_living_room:
    name: "Szenen"
    options:
      - --
      - Lesen
      - Sehr hell
      - Gedimmt
      - Konzentrieren
      - Energie tanken
      - Entspannen
      - Sonnenuntergang
      - Nordlicht
      - Fr체hling
    initial: '--'

scenes_bed_room:
    name: "Szenen"
    options:
      - --
      - Hell
      - Nachtlicht
      - Gedimmt
    initial: '--'

avr_source:
    name: AVR Quelle
    icon: mdi:playlist-play
    options:
        - --
        - Telekom
        - TV
        - AirPlay
        - Turntable
        - vTuner
        - Home Network

vacuum_rooms:
    name: R채ume
    icon: mdi:broom
    options:
        - --
        - Wohnzimmer
        - Schlafzimmer
        - B체ro
        - Katzenklo
        - Bad
        - K체che
        - Flur
        - Klo